apiVersion: v1
kind: Service
metadata:
  name: angie-chacon-service
  namespace: angie-chacon
  labels:
    app: microservicio-base
    owner: angie-chacon
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: microservicio-base
    owner: angie-chacon

